name: mmt_auto
description: Flutter project for "megamen" team. Lunyakov Alexey

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # ----- navigation ----- #
  desktop_window: ^0.4.0
  # go_router: ^12.1.1
  # ----- backend ----- #
  http: ^1.1.0
  # ----- video ----- #
  media_kit: ^1.1.10+1
  # ----- system ----- #
  path: ^1.8.3
  open_file: ^3.3.2
  file_picker: ^6.0.0
  restart_app: ^1.2.1
  image_picker: ^1.0.4
  url_launcher: ^6.1.14
  path_provider: ^2.1.1
  filesystem_picker: ^3.1.0
  # ----- icons ----- #
  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  # ----- data grid ----- #
  syncfusion_flutter_core: ^23.1.42
  syncfusion_flutter_datagrid: ^23.1.42


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets: 
    - assets/images/
    - assets/videos/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu-Regular.ttf
          weight: 400
        - asset: fonts/Ubuntu-Medium.ttf
          weight: 500
        - asset: fonts/Ubuntu-Bold.ttf
          weight: 700
